backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/images/products"
public_folder: "images/products"

collections:
  - name: "arts"
    label: "Command Center | Arts"
    folder: "source/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{identifier}}"
    fields:
      - { label: "Art Name", name: "product_name", widget: "string" }
      - { label: "Tags (post)", name: "tags", widget: "string" }
      - { label: "Identifier", name: "identifier", widget: "string" }
      - { label: "Section", name: "product_section", widget: "string" }
      - {
          label: "Product Description",
          name: "product_description",
          widget: "markdown",
        }
      - { label: "Art Image", name: "product_image", widget: "image" }
      - {
          label: "Art Image Alternative Text",
          name: "product_image_alternative_text",
          widget: "string",
        }
      - { label: "Members", name: "members", widget: "markdown" }
