backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/images/products"
public_folder: "/images/products"

collections:
  - name: "index"
    label: "Homepage"
    folder: "/source/commands/index"
    create: false
    fields:
      - {
          label: "Main Section Title",
          name: "main_section_title",
          widget: "string",
        }
      - {
          label: "Main Section Description",
          name: "main_section_description",
          widget: "markdown",
        }
      - {
          label: "First Section Title",
          name: "first_section_title",
          widget: "string",
        }
      - {
          label: "First Section Description",
          name: "first_section_description",
          widget: "markdown",
        }
      - {
          label: "First Section Image",
          name: "first_section_image",
          widget: "image",
        }
      - {
          label: "First Section Image Alt Text",
          name: "first_section_alternative_image",
          widget: "string",
        }

  - name: "arts"
    label: "Command Center | Arts"
    folder: "source/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{identifier}}"
    fields:
      - { label: "Art Name", name: "product_name", widget: "string" }
      - { label: "Tags (post)", name: "tags", widget: "string" }
      - { label: "Identifier", name: "identifier", widget: "string" }
      - { label: "Section", name: "product_section", widget: "string" }
      - {
          label: "Product Description",
          name: "product_description",
          widget: "markdown",
        }
      - { label: "Art Image", name: "product_image", widget: "image" }
      - {
          label: "Art Image Alternative Text",
          name: "product_image_alternative_text",
          widget: "string",
        }
      - { label: "Members", name: "members", widget: "markdown" }
